### ISSUE TITLE
After deleting a report from a folder, the remaining reports are not shown

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#652]
Do the following in the Test tab to see the error:

* Have a single report that exists in the root folder.
* Copy the report to a new foler "My folder".
* Select folder "My folder".
* Select the report in that folder.
* Press the delete button.
* In the confirmation dialog, the list of reports being deleted should have length one. This works fine.
* Press "Yes".
* The folder "My folder" is gone and the root folder is selected.
* See the error: no reports are shown anymore.
* Press refresh.
* See another error: still no reports are shown.
* Press the refresh button of the browser.
* Ok, the report that I expected is back.

**Comment by MatthijsSmets** [comment]
I dont see how this is a problem, in your steps you describe having only one report in the test tab. You move that report to its own folder, after which you delete the report. This causes the folder to be removed as well.
After that you describe that refreshing the test tab does not show any reports, which makes sense because you just deleted the only report that was in the test tab.
Could you clarify what the problem is exactly?
